---
- name: Ping all servers
  hosts: all
  gather_facts: false

  tasks:
    - name: Get filesystem disk usage
      ansible.builtin.command: "df -h --output=pcent,target"
      register: disk_usage
      changed_when: disk_usage.rc != 0

    - name: Find filesystems that are 90% or more occupied
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ disk_usage.stdout_lines }}"
      when: "item.split()[0].split('%')[0] | int >= 90"
