---
- name: Menuoper
  hosts: "{{ target_hostnames }}"
  gather_facts: true
  vars:
    ansible_user: "{{ target_ansible_user }}"
    ansible_password: "{{ target_ansible_password }}"

  tasks:
    # - name: Noop task
    #   ansible.builtin.meta: noop
    # - name: Menuper
    #   ansible.builtin.debug:
    #     msg: "{{ item.serv_desc }} - {{ item.serv_name }}"
    #   with_items: "{{ servers[ansible_hostname].services }}"
    # - name: debug
    #   ansible.builtin.debug:
    #     msg: "{{ inventory_hostname  }} - {{ dc  }}"
    #     var: hostvars[inventory_hostname]

    - name: Include_role my_role
      ansible.builtin.include_role:
        name: "my_role"
