---
- name: Menuoper
  hosts: "{{ target_hostnames  | default('all') }}"
  gather_facts: true
  vars:
    ansible_user: "{{ target_ansible_user | default('root') }}"
    ansible_password: "{{ target_ansible_password | default('none') }}"
  # vars:
  #   ansible_user: "{{ target_ansible_user | default('none') }}"
  #   ansible_password: "{{ target_ansible_password | default('none') }}"

  tasks:

    - name: Include_role my_role
      ansible.builtin.include_role:
        name: "my_role"
