---
- name: Check SolarWind Agent
  hosts: "{{ target_hostnames  | default('none') }}"
  gather_facts: true
  vars:
    ansible_user: "{{ target_ansible_user | default('none') }}"
    ansible_password: "{{ target_ansible_password | default('none') }}"

  tasks:

    - name: Get installed packages list
      ansible.builtin.package_facts:
        manager: rpm

    - name: Set agent_installed fact
      ansible.builtin.set_fact:
        agent_installed: "{{ 'true' if 'swiagent' in ansible_facts.packages else 'false' }}"

    # - name: Check if swiagent is installed
    #   ansible.builtin.debug:
    #     msg: >
    #       {% if 'swiagent' in ansible_facts.packages %}
    #         INFO: The swiagent is installed.
    #       {% else %}
    #         WARNING: The swiagent is NOT installed.
    #       {% endif %}

    - name: Get defined service list
      ansible.builtin.service_facts:

    # - name: Set agent_started fact
    #   set_fact:
    #     agent_started: "{{ 'true' if 'swiagent' in ansible_facts.packages else 'false' }}"

    - name: Set agent_started fact
      ansible.builtin.set_fact:
        agent_started: "{{ 'true' if ('swiagent' in ansible_facts.packages) and (ansible_facts.services['swiagentd.service'].state == 'running') else 'false' }}"


    - name: Check if swiagent service is active
      ansible.builtin.debug:
        msg: >
          {% if agent_installed %}
            INFO: The swiagent is installed and the service is {% if not agent_started %} NOT {% endif %} }} started.
          {% else %}
            WARNING: The swiagent service is NOT installed.
          {% endif %}



    # - name: Show information about a specific all services
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_facts.services }}"

    # - name: Check SolarWinds is Installed
    #   ansible.builtin.debug:
    #     msg:
    #       - "SolarWinds agent {{ 'is ' if 'swiagent' in ansible_facts.packages else 'is NOT' }} installed"

    # - name: Check SolarWinds is Active
    #   ansible.builtin.debug:
    #     msg:
    #       - "SolarWinds agent {{ 'is' if ansible_facts.services['swiagentd.service'].state == 'running' else 'is NOT' }} started"
    #   when: ('swiagent' in ansible_facts.packages)

    # - name: Check if swiagent service is active
    #   ansible.builtin.debug:
    #     msg: >
    #       {% if ansible_facts.services['swiagentd.service'].state == 'running' %}
    #         INFO: The swiagent service is active.
    #       {% else %}
    #         WARNING: The swiagent service is NOT active.
    #       {% endif %}
