- name: Ensure latest index.html is present
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'

- name: Whitelist httpd in firewalld
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true

- name: Ensure the 'automation' user exists
  ansible.builtin.user:
    name: automation
    password: "{{ automation_password | password_hash('sha512') }}"
