- name: "Ensure latest index.html is present"
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: "Whitelist httpd in firewalld"
  firewalld:
    service: http
    state: enabled
    permanent: true

- name: Ensure the 'automation' user exists
  ansible.builtin.user:
    name: automation
    password: "{{ automation_password | password_hash('sha512') }}"
    