---

- name: Include tasks for Debian-based systems
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Include tasks for RedHat-based systems
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Include common tasks
  ansible.builtin.include_tasks: common.yml

- name: Include menuoper tasks
  ansible.builtin.include_tasks: menu.yml

- name: Print vars
  ansible.builtin.debug:
    msg: "Servidor {{ inventory_hostname_short | lower }}  Env: {{ env }} Group: {{ group }} DC: {{ dc }} Services: {{ services }}"
