---

- name: Include tasks for Debian-based systems
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Include tasks for RedHat-based systems
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- include_tasks: common.yml   
- include_tasks: menu.yml      


- name: Print vars
  debug:
    msg: "Servidor {{inventory_hostname_short|lower}}  Env: {{env}} Group: {{group}} DC: {{dc}} Services: {{services}}"

