---

# tasks file for menuoper
- name: Create a unix user group - oper
  become: true
  become_user: root
  tags: menuoper,groupcreate
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    gid: "{{ item.gid }}"
  with_items:
    - { name: "oper", gid: "11000", state: "present" }

- name: Create a unix user oper
  become: true
  become_user: root
  tags: menuoper,usercreate
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    state: "{{ item.state }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
  with_items:
    - {name: "oper", comment: "oper user", uid: "11000", state: "present", group: "oper", groups: "", password: "!", shell: "/bin/bash"}

- name: Create directories
  become: true
  become_user: root
  tags: menuoper,dirs
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "/home/oper/.menu", owner: "oper", group: "oper", state: "directory", mode: '0755' }
    - { dest: "/home/oper/.menu/app", owner: "oper", group: "oper", state: "directory", mode: '0755' }
    - { dest: "/home/oper/scripts", owner: "oper", group: "oper", state: "directory", mode: '0755' }

- name: Copy required files
  become: true
  tags: menuoper,cpfiles
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - { src: "gomenu", dest: "/home/oper/scripts/gomenu", mode: "755", owner: "oper", group: "oper" }
    - { src: "bash_profile", dest: "/home/oper/.bash_profile", mode: "644", owner: "oper", group: "oper" }
    - { src: "motd", dest: "/etc/motd", mode: "644", owner: "root", group: "root" }
    - { src: "check_environment.sh", dest: "/home/oper/scripts/check_environment.sh", mode: "755", owner: "oper", group: "oper" }


- name: Main menuoper files
  become: true
  tags: menuoper
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - { src: 'menu/main.mnu.j2', dest: "/home/oper/.menu/main.mnu", owner: "oper", mode: "0664", group: "oper" }
    - { src: 'menu/app/main.mnu.j2', dest: "/home/oper/.menu/app/main.mnu", owner: "oper", mode: "0664", group: "oper" }

- name: Inicializar variable contador
  ansible.builtin.set_fact:
    contador: 0

- name: Include tasks menu_items.yml
  tags: menuoper
  ansible.builtin.include_tasks: "menu_items.yml"
  loop: "{{ menuoper_services }}"
  loop_control:
    index_var: contador
    loop_var: item_srv

- name: Add sudo rules to operator and validate the sudoers file before saving
  tags: menuoper
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: root
    group: root
    mode: '0440'
    create: true
    validate: /usr/sbin/visudo -cf %s
  with_items:
    - { path: "/etc/sudoers.d/sudo-oper", state: "present", regexp: "^User_Alias OPERADOR = oper", line: "User_Alias OPERADOR = oper" }
