---
- name: "Ensure required packages are present for Redhat"
  ansible.builtin.yum:
    state: present
    name: "{{ pkg_list_rh }}"

- name: "Ensure httpd service is started and enabled on Redhat"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ svc_list_rh }}"
