---
- name: "Packages update are present for Debian"
  ansible.builtin.apt:
    update_cache: true

- name: "Ensure required packages are present for Debian"
  ansible.builtin.apt:
    name: "{{ pkg_list_ubu }}"
    state: present

- name: "Ensure httpd service is started and enabled on Debain"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ svc_list_ubu }}"
