---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
    - name: include role my_role
      include_role:
        name: "/mnt/c/Users/80020377/Ansible/my_role"
