---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#  set -e
#  yamllint .
#  ansible-lint
platforms:
  # - name: centos8-server
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  # - name: Linux-instance
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  - name: testing-server1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    # cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    host_vars:
      testing-server1:
        env: "PRO"
        group: "ENTORNO"
        dc: "AUS"
        menuoper_services:
          - serv_desc: "Apache"
            serv_name: "apache2.service"
          - serv_desc: "Firewall"
            serv_name: "firewalld.service"
          - serv_desc: "Qualis Agent"
            serv_name: "qualis.service"
          - serv_desc: "SolarWinds Agent"
            serv_name: "solarwinds.service"
          - serv_desc: "FalconSensor Agent"
            serv_name: "falcon.service"
          - serv_desc: "Oracle Database labdb"
            serv_name: "ora_labdd.service"
scenario:
  name: default
verifier:
  name: ansible
