---
dependency:
  name: galaxy
driver:
  name: docker
#lint: |
#  set -e
#  yamllint .
#  ansible-lint
platforms:
  # - name: centos8-server
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  # - name: Linux-instance
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    #cgroupns_mode: host
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible
