---

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  # - name: Include test_my_role
  #   ansible.builtin.include_role:
  #     name: "my_role"
  #     #task_from: init
  - name: Verify Apache is serving web requests
    ansible.builtin.uri:
      url: http://localhost
      status_code: 200
  - name: Include test_my_role
    ansible.builtin.include_role:
      name: "test_my_role"
  #     #task_from: init

