# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "devel-menuoper" ]
#  pull_request:
#    branches: [ "devel-menuoper" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
 #   strategy:
 #     matrix:
 #       distro:
 #         - rockylinux8
 #         - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule --debug create
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          #MOLECULE_DISTRO: ${{ matrix.distro }}
        working-directory: molecule
