# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "devel-menuoper" ]
  pull_request:
    branches: [ "devel-menuoper" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Molecule
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # services:
    #   docker:
    #     name: docker
    #     image: docker:20.10.7
    #     options: --privileged
    #     ports:
    #       - 2375:2375
    #     volumes:
    #       - /var/run/docker.sock:/var/run/docker.sock
          
    strategy:
      matrix:
        # distro:
        #  - centos8
        #  - ubuntu22
        python-version:
          - 3.8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the codebase 
        uses: actions/checkout@v4
      
      - name: Set up Python 3 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}          

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-docker ansible

      # remove containerd
      - name: Ensure  remove --purge containerd containerd.io
        run: sudo apt-get remove --purge containerd containerd.io
        
      # Set up Docker (Optional)
      - name: Ensure Docker is installed
        run: sudo apt-get install docker.io
        
      # Authenticate to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Pull the required Docker image Centos8
      - name: Pull Docker image - CentOS 8
        run: docker pull geerlingguy/docker-centos8-ansible:latest

      # Pull the required Docker image ubuntu2204-ansible:latest
      - name: Pull Docker image - Ubuntu2204
        run: docker pull geerlingguy/docker-ubuntu2204-ansible:latest
        
        

      # Run Molecule tests
      - name: Run Molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'


          
          
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!
        

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
