---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          # - centos7 #failts due it has no python3
          - debian10
          - ubuntu2204
          - fedora37
          - fedora39
        python-version:
          - 3.9.x      

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker yamllint ansible-lint

      - name: Install test list dependencies.
        run: pip3 list

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
