---
- name: "Check httpd package status for Redhat"
  ansible.builtin.package:
    name: "httpd"
    state: "installed"
  check_mode: true
  register: pkg_status_rh
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Test httpd package is installed for Redhat"
  ansible.builtin.assert:
    that:
      - not pkg_status_rh.changed
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Check httpd package status for Debian"
  ansible.builtin.package:
    name: "apache2"
    state: "present"
  check_mode: true
  register: pkg_status_ubu
  when: ansible_facts['os_family'] == 'Debian'

- name: "Test apache2 package is installed for Debian"
  ansible.builtin.assert:
    that:
      - not pkg_status_ubu.changed
  when: ansible_facts['os_family'] == 'Debian'

- name: Verify Apache is serving web requests.
  ansible.builtin.uri:
    url: http://localhost/
    status_code: 200
